### ISSUE TITLE
Unable to open a database that was created with Keepass Windows version (several years ago).

### ISSUE THREAD

**Issue by franco27** [OneKeePass/mobile#15]
Hello.

I am unable to open the database. Your application gives me an error message.

However, I have no problem opening this database with other Keepass applications or forks (clones). I have been using this database for several years.

The initial database was created with the Windows version of Keepass.

I created a new database with your application, but there is no option to import this database.

I have a lot of passwords stored in this database, and I cannot imagine manually inputting them one by one into your application.

![IMG_20231129_002745.jpg](https://github.com/OneKeePass/mobile/assets/31793920/2b896ef1-a9ab-4519-91cc-e1b898731fb3)

**Comment by jeyasankar** [comment]
Hi @franco27 ,

Thanks trying the app.  Currently OneKeePass supports only the KeePass database format 4.  

If you want to use OneKeePass, you may try to save your old database  using the latest KeePass windows application ( v2.59 ) to save in format 4  which uses ChaCha20 and Argon 2d. 

Then if you want, you can use OneKeePass to open that file 

Otherwise, please continue with other apps which supports the old database formats

**Comment by franco27** [comment]
Thank you for responding to me and explaining the process for opening the database.

**Comment by TBugReporter** [comment]
Why is this marked "completed"?  While AES-256 / ChaCha20 may be a worthy goal, forcing them on people is not.  Interoperability requires being compatible with old standards and old programs that haven't been updated.  I wanted to try your app, but because of this, I won't.

**Comment by jeyasankar** [comment]
Hi @TBugReporter ,

I marked 'completed' for now.  I will try to add this feature of opening old format database later sometime (it will take sometime). This can be done only after all other important features are done

**Comment by TBugReporter** [comment]
Thank you for your response.  I don't understand how the "completed" tag applies here, as opposed to "will-complete-eventually" or something similar, but it's your project; if that works for you, you're entitled to manage your project however you see fit.
