### ISSUE TITLE
International Translation

### ISSUE THREAD

**Issue by ggbce** [OneKeePass/mobile#18]
### Please agree to the following

- [X] I have searched [existing issues](https://github.com/OneKeePass/mobile/issues?q=) for duplicates
- [X] I agree to follow this project's [Code of Conduct](https://github.com/OneKeePass/mobile/blob/develop/.github/CODE_OF_CONDUCT.md)

### Summary

Add language !

### Motivation

Like many billions other people around the world English is not my primary language even if I use it ! In goal to use this application, share it with other person that can't understand English, it's more complicated.

Adding most common languages used in Africa, Americas and Europe could be a good startup !!!

- Deutsch
- French
- Spanish
- Italian
- Portuguese

### Anything else?

If you need help to translate. I will happy to help you. Just send me a list of labels/tags/fields in English where I could give you the French version.

**Comment by jeyasankar** [comment]
Hi @ggbce ,

Thanks for the ticket. 

I agree that without multi language support, the apps uses are restricted to English only. I will be adding the translation mechanism and use of such translations in the apps.  

For mobile apps, I have done some base works in the apps code for the multi language supports, but I need yet to start similar works for desktop applications

I will certainly take your help for any translation works when these code changes are in place

**Comment by jeyasankar** [comment]
Hi @ggbce,

With the recent release, the app has now translation supports. For now I have added French and Spanish translations. Please have a look and let me know 

I would appreciate any translation supports for any other language by you!  I have created a repo - [OneKeePass Translations](https://github.com/OneKeePass/onekeepass-translations) for this where new languages can be added

Thanks
