### ISSUE TITLE
tell user of KDBX old version incompatible

### ISSUE THREAD

**Issue by jwmh** [OneKeePass/mobile#2]
### Please agree to the following

- [X] I have searched [existing issues](https://github.com/OneKeePass/mobile/issues?q=) for duplicates
- [X] I agree to follow this project's [Code of Conduct](https://github.com/OneKeePass/mobile/blob/develop/.github/CODE_OF_CONDUCT.md)

### Summary

tell user of KDBX old version incompatible 

### Motivation

Currently when I attempt to open a previously-created KDBX v3 db,
the iOS app just says,
“Database Open Error
The database file is not a valid one.”

It should also say,
“If you’re able to open this in other KeePass-compatible apps and the file extension ends in .kdbx, then this might be because the db is an older version (prior to kdbx v4).

As of this writing, this app only supports opening the latest version of keepass databases, which is kdbx version 4.
“

**Comment by jeyasankar** [comment]
Thanks for identifying the issue and creating the issue ticket with a nice explanation . I will fix this one and include the fix in the next release which should be in about 3 weeks time

**Comment by jeyasankar** [comment]
Release 0.7.0 fixed the issue by adding proper error messages when user attempts to open a database with old format
