### ISSUE TITLE
File Pick Error

### ISSUE THREAD

**Issue by matths** [OneKeePass/mobile#5]
### Please agree to the following

- [X] I have searched [existing issues](https://github.com/OneKeePass/mobile/issues?q=) for duplicates
- [X] I agree to follow this project's [Code of Conduct](https://github.com/OneKeePass/mobile/blob/develop/.github/CODE_OF_CONDUCT.md)

### Summary

When using the mobile app on desktop files can't be open.

### Steps To Reproduce

1. Go to the Mac AppStore and search for OneKeePass
2. Switch from Mac to iOS/iPad Apps
3. Install the mobile app as Desktop app (possible with recent version of Mac OSX)
4. Run the app and try to open your demo.kdbx file you created e.g. with the OneKeePass Desktop app
5. you will see a Dialog stating that there is a File Pick Error

### Expected Result

I would really appreciate, if you could have a look into that as it would be cool to have the same UI for iOS and Desktop. I know that you provide a Desktop client which is working fine, and I just recently found out about running iOS apps in OSX, but I would really enjoy if it would be seamless work.

### Actual Result

Interaction with files seems to be not working.

### Screenshots or Videos

<img width="635" alt="screen" src="https://github.com/OneKeePass/mobile/assets/264769/4e7030e2-f576-48c6-924b-5f4c5493239f">

### Operating System

iOS

### Operating System Version

OSX Ventura 13.4.1

### Device

MacBook Air M2 2022

### Build Version

Version 0.7.0 (1)

**Comment by jeyasankar** [comment]
Hi Matthias, 
Thanks for creating the ticket. Though there is a separate Desktop client available, I agree with you that making the iOS app to work in OSX  also will  give a  seamless user experience for the  user

**Comment by jeyasankar** [comment]
For now I am closing this and will consider this feature later sometime
