### ISSUE TITLE
Password masking not working on entry 'View' and 'Edit' in Android app. 

### ISSUE THREAD

**Issue by gregordinary** [OneKeePass/mobile#6]
### Please agree to the following

- [X] I have searched [existing issues](https://github.com/OneKeePass/mobile/issues?q=) for duplicates
- [X] I agree to follow this project's [Code of Conduct](https://github.com/OneKeePass/mobile/blob/develop/.github/CODE_OF_CONDUCT.md)

### Summary

Clicking the 'eye' icon while viewing or editing an entry in the OneKeePass Android App has no effect, the password is always visible. 

### Steps To Reproduce

1. Create or Open a KeePass DB
2. Click **+** on the lower right and select **Add Entry**
3. Type or generate a password in the password field. 
4. Click the "eye" logo to toggle password masking on/off
5. Nothing happens, the password remains visible. 
6. Save the entry.
7. Now when in "view" mode for the entry, again click the "eye" logo to toggle password masking on/off. 
8. Nothing happens, the password remains visible. 

### Expected Result

When clicking the "eye" icon to toggle password visibility, it should switch on/off.

### Actual Result

Clicking the "eye" icon repeatedly to toggle password visibility does nothing. The password is always visible. 

### Screenshots or Videos

Edit mode with "eye" logo crossed out:

![Screenshot_20230808-165306308](https://github.com/OneKeePass/mobile/assets/33880035/a7f1ea29-5ba0-416e-804a-3b8e4aa937e2)

Edit mode with "eye" logo normal:
![Screenshot_20230808-165312963](https://github.com/OneKeePass/mobile/assets/33880035/0ce2f187-e332-482e-9902-29ca9e23f8a0)

View mode with "eye" logo crossed out:
![Screenshot_20230808-165259702](https://github.com/OneKeePass/mobile/assets/33880035/67e52ce1-45ff-4217-9780-a4d7d9bd9f4e)

View mode with "eye" logo normal:
![Screenshot_20230808-165254342](https://github.com/OneKeePass/mobile/assets/33880035/7e112339-a07c-4414-b505-90c1f6108c17)

### Operating System

Android

### Operating System Version

13

### Device

Asus Zenfone 8 Flip

### Build Version

0.7.0

**Comment by jeyasankar** [comment]
Hi gregordinary,
Thanks for creating the ticket with the details. In the next release, this bug will be fixed

**Comment by jeyasankar** [comment]
Fixed in release 0.8.0.
