### ISSUE TITLE
Back button minimizes when it should return to previous screen

### ISSUE THREAD

**Issue by gregordinary** [OneKeePass/mobile#8]
### Please agree to the following

- [X] I have searched [existing issues](https://github.com/OneKeePass/mobile/issues?q=) for duplicates
- [X] I agree to follow this project's [Code of Conduct](https://github.com/OneKeePass/mobile/blob/develop/.github/CODE_OF_CONDUCT.md)

### Summary

When going through a multi-step process like editing fields within an entry, pressing the "back button" on Android won't return to the previous window, it instead minimizes the application.

### Steps To Reproduce

1. Open OneKeePass on Android
2. Click an existing entry OR click + to create a new entry
3. Click the ◁ back icon on Android (the native system icon, not the App Icon)
4. Typically this would return to a previous screen and only minimize an app if it's on the Home/Initial screen, however no matter what window you're in within OneKeePass, the ◁ Android back icon will minimize the application. 

### Expected Result

Clicking the Android ◁ back button should return to the previous screen _within_ OneKeePass, unless it is on the home screen, in which case it can minimize after (typically) two taps of the back button. 

### Actual Result

Clicking the Android ◁ back button on **any** screen within OneKeePass results in the application minimizing. 

### Operating System

Android

### Operating System Version

13

### Device

Asus Zenfone 8 Flip

### Build Version

0.7.0

**Comment by jeyasankar** [comment]
Thanks gregordinary. I will take a look.
