### ISSUE TITLE
Password Generate Button has UI Overlap

### ISSUE THREAD

**Issue by gregordinary** [OneKeePass/mobile#9]
### Please agree to the following

- [X] I have searched [existing issues](https://github.com/OneKeePass/mobile/issues?q=) for duplicates
- [X] I agree to follow this project's [Code of Conduct](https://github.com/OneKeePass/mobile/blob/develop/.github/CODE_OF_CONDUCT.md)

### Summary

The password generate button  🗘 overlays the outline of the password text box.

### Steps To Reproduce

1. Open the Android App
2. Click to view an entry
3. The password generate button  🗘 overlays the border lines of the password text box. 

### Expected Result

The password generate button  🗘 should fit within the borders of the password text box. 

### Actual Result

The password generate icon  🗘 overlaps with the password entry text box and the overall frame.

### Screenshots or Videos

![Screenshot_20230808-191645657](https://github.com/OneKeePass/mobile/assets/33880035/bc88fa43-3e1b-4aa8-b69a-1f6509c9fa06)

### Additional Context

I think the  password generate button  🗘 may not be using a transparent background, or its ordering/layering is placed too far forward and is causing the overlap (not quite sure). 

### Operating System

Android

### Operating System Version

13

### Device

Asus Zenfone 8 Flip

### Build Version

0.7.0

**Comment by jeyasankar** [comment]
Thanks gregordinary. I will take a look and fix this

**Comment by jeyasankar** [comment]
Fixed in release 0.8.0.
